In [50]:
#1.	Write a Python Program to find sum of array?
import numpy as np
arr=np.array([1,3,56,7,74])
s=sum(arr)
print(s)
np.append(arr,8)

141


array([ 1,  3, 56,  7, 74,  8])

In [21]:
#2.	Write a Python Program to find largest element in an array?
import numpy as np
arr=np.array([1,3,56,100,7,74,6])
l=arr[0]
for i in range(1,len(arr)):
    if arr[i]>l:
        l=arr[i]
print(l)                 

100


In [64]:
#3.	Write a Python Program for array rotation?
#rotating by 3 position
import numpy as np
arr=np.array([1,3,56,7,74,3,6,8])
n=3
new_arr=np.array([])
for j in range(n,len(arr)):
    new_arr=np.append(new_arr,arr[j])
for j in range(n):
    new_arr=np.append(new_arr,arr[j])
    
print(arr)
print(new_arr)

[ 1  3 56  7 74  3  6  8]
[ 7. 74.  3.  6.  8.  1.  3. 56.]


In [41]:
#4.	Write a Python Program to Split the array and add the first part to the end?
arr=np.array([1,3,56,7,74,3,6,8])
n=len(arr)//2
first=arr[:n]
last=arr[n:]

new_arr=np.append(last,first)
print(arr)
print(new_arr)

[ 1  3 56  7 74  3  6  8]
[74  3  6  8  1  3 56  7]


In [44]:
#5.	Write a Python Program to check if given array is Monotonic?
arr=np.array([1,3,76,5,7])
inc=True
dec=True
for i in range(len(arr)-1):
    if arr[i+1]>arr[i]:
        dec=False
        break
for i in range(len(arr)-1):
    if arr[i+1]<arr[i]:
        inc=False
        break
if inc or dec:
    print('array is monotonic')
else:
     print('array is not monotonic')

array is not monotonic
